### ISSUE TITLE
Qadastre2OSM: Option --convert-with-lands

### ISSUE THREAD

**Issue by teymour** [osm-fr/export-cadastre#19]
Bonjour,

J'aurai souhaité récupérer les informations relatives aux parcelles définies pour une ville (Mittelwihr) via Qadastre2OSM. J'ai donc utilisé l'option --convert-with-lands :
 
> $ Qadastre2OSM --convert-with-lands 68630 Mittelwihr

mais elle semble générer les même fichiers que pour --convert :

> $ md5sum *osm
> a7185fbfe92f498ed28de13b615445ad  68630-Mittelwihr-city-limit.osm
> 84220c9fd917c96ee8ea06822ec6c23e  68630-Mittelwihr-houses.osm
> c7cd14684331184191bb265e70d3d50d  68630-Mittelwihr-water.osm
> $ rm *osm
> $ Qadastre2OSM --convert 68630 Mittelwihr
> $ md5sum *osm
> a7185fbfe92f498ed28de13b615445ad  68630-Mittelwihr-city-limit.osm
> 84220c9fd917c96ee8ea06822ec6c23e  68630-Mittelwihr-houses.osm
> c7cd14684331184191bb265e70d3d50d  68630-Mittelwihr-water.osm

Ai-je oublié des paramètres ? Cette option est-elle maintenue ?

**Comment by sletuffe** [comment]
La version maintenue se trouve là : https://gitorious.org/qadastre
Ici, on a qu'une copie ancienne du programme qui suffit à notre besoin

**Comment by teymour** [comment]
Le 09/02/2015 17:12, sly - sylvain letuffe a écrit :
> La version maintenue se trouve là : https://gitorious.org/qadastre
> Ici, on a qu'une copie ancienne du programme qui suffit à notre besoin

Merci Sylvain pour votre réponse.

J'avais effectivement regardé le dépôt du projet originel mais il m'a
semblé moins que le votre notamment car il ne proposait pas d'export des
limites de la commune.

Je vais donc partir sur un mix des deux.

Merci encore,

Tangui
