### ISSUE TITLE
Export des communes nouvelles dans l'Orne

### ISSUE THREAD

**Issue by thibhul** [osm-fr/export-cadastre#21]
Bonjour,

Je me suis attaqué récemment à l'import cadastre des communes de l'Orne, toutefois je rencontre un problème lorsque j'exporte les communes nouvelles: seule la commune principale de la commune nouvelle est exportée et en plus à des coordonnées complètement décalées. J'ai joint le fichier fautif
[OD230-LONGNY LES VILLAGES-houses-simplifie.osm.zip](https://github.com/osm-fr/export-cadastre/files/726991/OD230-LONGNY.LES.VILLAGES-houses-simplifie.osm.zip).
J'ai d'ailleurs remarqué un problème semblable avec la couche cadastre, mais pas avec BANO curieusement.

**Comment by tyndare** [comment]
Effectivement. C’est dû à un problème de fichiers temporaires non effacés sur le serveur cadastre.openstreetmap.fr. Il mélange des anciens exports avec les nouvelles limites.
J'essaye de régler ça pour demain.

**Comment by tyndare** [comment]
Normallement c'est corrigé

[OD230-LONGNY LES VILLAGES.zip](https://github.com/osm-fr/export-cadastre/files/729243/OD230-LONGNY.LES.VILLAGES.zip)
