### ISSUE TITLE
https non fonctionnel pour "Sélectionner une zone à exporter"

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/export-cadastre#31]
"Sélectionner une zone à exporter" ne fonctionne pas en https à cause d'une mixed content http<>https
la modif des fichiers leaflet ayant du http codé en dur ne fonctionne pas parce que certains url n'ont pas le bon certificat comme par exemple  http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css
peu-être serrait ce l'occasion de faire une maj leaflet dont la version 1.3.4 est sortie...

**Comment by Marc-marc-marc** [comment]
en regardant la doc de la dernière version, une autre url existe en https, ex https://unpkg.com/leaflet@0.7.2/dist/leaflet.css
voir la discussion dans https://github.com/osm-fr/export-cadastre/pull/27

**Comment by vdct** [comment]
Je pense qu'il faut surtout se poser la question du futur de cette page avec sa techno actuelle. Elle s'appuie en backend sur la récupération des PDFs du cadastre, qui n'est plus à encourager en la présence des adresses et du bâti du cadastre sur https://cadastre.data.gouv.fr/ et https://adresse.data.gouv.fr/. Donc refonte à prévoir, qui inclut le ticket actuel mais pas que.

**Comment by Marc-marc-marc** [comment]
résolu avec https://github.com/osm-fr/export-cadastre/pull/36
on ferra un autre ticket pour résumer la discussion de fond quand à la techno (pdf<>
