### ISSUE TITLE
configurer les entêtes CORS

### ISSUE THREAD

**Issue by bagage** [osm-fr/export-cadastre#34]
Visiblement le serveur apache n'est pas configuré pour CORS, il manque le header `Access-Control-Allow-Origin: *` : 

```sh
$ curl  --verbose https://cadastre.openstreetmap.fr/data/055/MA430-RIBEAUCOURT-houses-simplifie.osm -H "Origin: http://example.com" \
  -H "Access-Control-Request-Method: POST" \
  -H "Access-Control-Request-Headers: X-Requested-With" \
  -X OPTIONS

*   Trying 88.191.250.198...
* TCP_NODELAY set
* Connected to cadastre.openstreetmap.fr (88.191.250.198) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=osm104.openstreetmap.fr
*  start date: Sep  5 00:45:21 2018 GMT
*  expire date: Dec  4 00:45:21 2018 GMT
*  subjectAltName: host "cadastre.openstreetmap.fr" matched cert's "cadastre.openstreetmap.fr"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> OPTIONS /data/055/MA430-RIBEAUCOURT-houses-simplifie.osm HTTP/1.1
> Host: cadastre.openstreetmap.fr
> User-Agent: curl/7.61.0
> Accept: */*
> Origin: http://example.com
> Access-Control-Request-Method: POST
> Access-Control-Request-Headers: X-Requested-With
> 
< HTTP/1.1 200 OK
< Date: Tue, 30 Oct 2018 22:08:09 GMT
< Server: Apache/2.2.22 (Debian)
< Allow: POST,OPTIONS,GET,HEAD
< Content-Length: 0
< 
* Connection #0 to host cadastre.openstreetmap.fr left intact
```

**Comment by Marc-marc-marc** [comment]
Pas sur qu'il y ai besoin de faire un http POST pour cela
mais pas de raison non plus de ne pas activer CORS sur ce vhost.
modif faite sur le serveur commit c824ed444614bfe9a2dbf84d6433706953b02ec4
a2enmod headers
+++ /etc/apache2/sites-available/vhost-cadastre.openstreetmap.fr
+        #Marc_marc pour https://github.com/osm-fr/export-cadastre/issues/34
+       Header set Access-Control-Allow-Origin "*"
apache reload, à tester

**Comment by bagage** [comment]
Dans l'idée ça fonctionne bien pour moi, merci ! Dans le cas d'un fichier existant, le serveur renvoie bien l'entête c'est parfait.

Par contre il reste un petit soucis dans le cas où on requête un fichier inexistant : le serveur renvoie bien `404 Not Found`, par contre l'entête `Access-Control-Allow-Origin` n'est pas positionné dans ce cas. Exemple pour : 

```
$ curl https://cadastre.openstreetmap.fr/data/055/MA430-RIBEAUCOURT-houses-prediction_segmente.osm --verbose

< HTTP/1.1 404 Not Found
< Date: Wed, 31 Oct 2018 17:10:24 GMT
< Server: Apache/2.2.22 (Debian)
< Vary: Accept-Encoding
< Content-Length: 346
< Content-Type: text/html; charset=iso-8859-1
```

Dans un cas où le fichier existe : 

```
$ curl https://cadastre.openstreetmap.fr/data/055/MA430-RIBEAUCOURT-houses.osm --verbose

< HTTP/1.1 200 OK
< Date: Wed, 31 Oct 2018 17:10:14 GMT
< Server: Apache/2.2.22 (Debian)
< Last-Modified: Sun, 09 Sep 2018 15:50:57 GMT
< ETag: "144ba57-1e460-5757234e1dff8"
< Accept-Ranges: bytes
< Content-Length: 124000
< Access-Control-Allow-Origin: *
```

**Comment by Bibi56** [comment]
A priori si on crée une page pour les 404, ça devrait être réglé, sinon on peut le faire plus proprement : https://httpd.apache.org/docs/2.2/custom-error.html

**Comment by jocelynj** [comment]
@Bibi56, je ne comprends pas trop comment créer une page pour les 404 qui aurait le header CORS.

Est-ce que tu saurais ce qu'il faut mettre dans la config apache ?

**Comment by Bibi56** [comment]
@jocelynj je dirais quelque chose comme :
`ErrorDocument 404 /errors/not_found.html `
mais c'est juste ce que je lis dans la doc, je n'ai pas testé.

**Comment by jocelynj** [comment]
En épluchant la doc d'apache sur https://httpd.apache.org/docs/current/fr/mod/mod_headers.html#header, il suffit de rajouter `always` sur  `Header set Access-Control-Allow-Origin "*"`

@bagage: tu pourrais retester ?

**Comment by bagage** [comment]
@jocelynj si le `curl` au dessus est OK, je suis OK ! Et ça a l'air tout bon, impec :).
