### ISSUE TITLE
fichiers générés jamais nettoyés

### ISSUE THREAD

**Issue by bagage** [osm-fr/export-cadastre#35]
C'est peut-être lié à #23, mais visiblement les fichiers générés ne sont plus jamais nettoyés, depuis au moins le 6 juillet 2017

http://cadastre.openstreetmap.fr/data/018/?C=M;O=A

**Comment by jocelynj** [comment]
Combien de temps penses-tu que ces fichiers devraient rester ?

**Comment by jocelynj** [comment]
Le script était buggé, avec un `find ./ -mtime +7 -rm` que j'ai remplacé par `find ./ -mtime +31 -delete`

**Comment by bagage** [comment]
Super merci @jocelynj. Un mois ça paraît bien !
