### ISSUE TITLE
"Sélectionner une zone à exporter" non fonctionnel à cause d'une erreur de logique

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/export-cadastre#37]
après le correctif https://github.com/osm-fr/export-cadastre/issues/31,
"Sélectionner une zone à exporter" provoque une requête overpass du genre `node["ref:INSEE"="01002"]["place"]`
c'est une erreur de logique puisque le noeud représente le village et non la commune et que la confusion entre les 2 a fait l'objet d'un correctif récement dans les données osm.
il faut cibler la commune et vérifier si le code supporte de recevoir une relation ou s'il faut en plus utiliser `out center` pour simplifier la réponse en un point

**Comment by Marc-marc-marc** [comment]
à remplacer par `relation["ref:INSEE"="01002"][type=boundary][boundary=administrative]`

**Comment by bagage** [comment]
ok @vdct

**Comment by Marc-marc-marc** [comment]
corrigé par https://github.com/osm-fr/export-cadastre/pull/39
