### ISSUE TITLE
Tri des communes par ordre alphabétique

### ISSUE THREAD

**Issue by windu2b** [osm-fr/export-cadastre#4]
Les communes affichées dans la liste déroulante ne sont pas triées par ordre alphabétique : celle ayant une espace (qui devrait être un trait d'union) sont placées avant celles ayant un caractère alphabétique à la même position. 
Ex : MONT SAINT PERE (code INSEE 02524) est affiché avant MONTBREHAIN (code INSEE : 02500).
Le tri devrait donc se faire selon le code INSEE
![cadastre - tri alphabétique](https://f.cloud.github.com/assets/498286/131061/74afb97c-7047-11e2-9958-a9097247a517.png)

**Comment by sletuffe** [comment]
je pense qu'on peut clore, c'est sans importance maintenant (ou presque) vu qu'on a un moteur de recherche pour trouver les communes, ce qui est bien plus simple que par ordre alphabétique
